### ISSUE TITLE
angular integration

### ISSUE THREAD

**Issue by Fatxx** [typicode/pegasus#14]
How do you use pegasus alongside with Angular?

**Comment by typicode** [comment]
Hi André

Personally, I would try something like this:

```html
<script src="pegasus.min.js"></script>
<script>
  var requests = {}
  requests.posts = pegasus('/posts')
</script>

<!-- then load other libs (AngularJS, ...)  -->
```

```javascript
// In your Angular controller
if (requests.posts) {
  delete requests.post
  requests.posts.then(function (data) {
    $scope.posts = data
    $scope.$apply()
  })
} else {
  $scope.posts = Post.query()
}
```

The idea is that Pegasus should only be used to speed up the first request then you should use Angular's way of querying data.
This is why, in the example, there's a mechanism to load data from Pegasus once.

Hope this helps.

**Comment by bulutcy** [comment]
Helo,
Unfortunately, typicode's answer may not work for you since pegasus' response is different than angular's $http response object. I am currently making changes to make it work with angular.
Bulut.
