### ISSUE TITLE
Http methods support other then GET

### ISSUE THREAD

**Issue by bulutcy** [typicode/pegasus#17]
Hello,

Is it possible to add support for POST or any other http method?
I've updated the script to work with POST, I can make a pull request if it'd be useful for anyone.

Thanks.

**Comment by typicode** [comment]
Hi @bulutcy 

Thanks for the offer :)

Personally, I prefer to only support `GET`. Mainly to keep the library as small as possible. The idea being that the smaller it is, the faster it loads and can start making requests.

However, feel free to link to your fork or post your code in this issue if you want. It may help others.
