### ISSUE TITLE
"Cannot find module './charset.js'"

### ISSUE THREAD

**Issue by lpender** [typicode/pegasus#19]
I get this error when trying to compile your plugin with Browserify.

i.e.

```
_ajax = require('pegasus');
```

Produces:

```
Cannot find module './charset.js'
```

Thoughts?

**Comment by lpender** [comment]
Looks like an issue with `karma-browserify` potentially.

**Comment by lpender** [comment]
I thought was an issue with `karma-browserify` but I was wrong. It doesn't compile with regular `browserify` either. Seemed to work fine with `webpack` when I was using it earlier...

**Comment by lpender** [comment]
Here's a more detailed stack trace:

```
Uncaught Error: Cannot find module './charset.js'                                                                                     │├── vinyl@0.5.3 (clone-stats@0.0.1, replace-ext@0.0.1, clone@1.0.2)
  at /var/folders/49/k6ntv7wd5p74912pj6kp456c0000gp/T/2e0eb91fcce722e8eb3d9dd2e3075ce9.browserify:1 <- node_modules/karma-browserify/nod│└── webpack@1.12.11 (interpret@0.6.6, tapable@0.1.10, clone@1.0.2, async@1.5.2, esprima@2.7.1, supports-color@3.1.2, enhanced-resolve@0
e_modules/browserify/node_modules/browser-pack/_prelude.js:1:0
```

**Comment by typicode** [comment]
Actually pegasus on npm is available under a scope. To get the right module, you need to install it using `npm install @typicode/pegasus`. It should fix the error.
